apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uq84o2w4o-java-springboot 
  janus-idp.io/tekton: uq84o2w4o-java-springboot
  backstage.io/kubernetes-id: uq84o2w4o-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uq84o2w4o-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  